### ISSUE TITLE
Assert fail in get_root_func

### ISSUE THREAD

**Issue by pjsg** [dmclain/django-debug-toolbar-line-profiler#11]
I get a repeatable assert failure in get_root_func when I go to the root page of my website. The other pages appear to work. From playing around in the debugger, there is *lots* of data returned by self.stats.items()

**Comment by dmclain** [comment]
The assert is removed in v0.5.1 by 8424d55. Try `pip install django-debug-toolbar-line-profiler==0.5.1` and the assert failure shouldn't happen any more.

It's not clear to me what would cause the root function not to be detected correctly, and there may not be any actual output in the panel for your root page. If you have any additional details, I'd love to hear them.
