### ISSUE TITLE
How to open line stack from other trace members?

### ISSUE THREAD

**Issue by Gwildor** [dmclain/django-debug-toolbar-line-profiler#3]
I'm probably missing something extremely obvious here, or I've hit a bug, but I can't seem to open nor close the line number data for any of the functions called. When I open the panel, I see a nice stack trace starting from `django/views/generic/base.py in view` all the way down to `/debug_toolbar/panels/sql/tracking.py in execute`, with stuff like Django's database layer and my own view in between. This is exactly like debug toolbar's own profiling panel. One thing that is noticibly different is that between the first and second row, there is a big table with the whole code of the `view` function which is returned by the `as_view` function in Django's `View` class, with the line numbers next to it and data such as times hit and total time. This is the behaviour I expected, so thus far everything is working correctly.

But then I try to toggle the data from the other views, which does nothing. I can't seem to find anything in the DOM of the page either. I notice the `tr.djToggleDetails`, but the other rows don't have anything like that in between. From down there it is all `tr.djDebugProfileRow`. One thing of interest is that those rows all have classes which don't seem very appropriate and seem to stack based on the depth. For instance, I have a row `tr.djDebugProfileRow.djToggleDetails_0.djToggleDetails_0_3 djSelected`, but below that is also a row `tr.djDebugProfileRow.djToggleDetails_0.djToggleDetails_0_3.djToggleDetails_0_3_2.djToggleDetails_0_3_2_1.djToggleDetails_0_3_2_1_2.djToggleDetails_0_3_2_1_2_7.djToggleDetails_0_3_2_1_2_7_5.djSelected`

**Comment by svengt** [comment]
I know this is an old issue but I was having the same problem. It seems that when you wrap the as_view method with something like never_cache e.g. `url(r'^test/$', never_cache(Test.as_view()), name='test'),` the profiler is not able to profile the view. To work around this problem I changed never_cache to a lambda when debug mode is enabled.

```
# Really never_cache
never_cache = cache_control(no_cache=True, no_store=True, must_revalidate=True, max_age=0)

if settings.DEBUG:
    never_cache = lambda x: x

urlpatterns = patterns('',
    ...
    url(r'^test/$', never_cache(Test.as_view()), name='test'),
)
```
