### ISSUE TITLE
Profiling panel shows only a single line

### ISSUE THREAD

**Issue by 8one6** [dmclain/django-debug-toolbar-line-profiler#4]
I have django-debug-toolbar installed and working, but when I look at the profiling panel, I only get one line of results.  I am calling a simple class-based view built on `TemplateView`.  So I have written a custom implementation of `get_context_data`.  So to be clear, it's the execution of that method that I most want to profile.  However the only line I get back says:

    {method 'disable' of '_lsprof.Profiler' objects}

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/4360170/2562202/bdd92fca-b83f-11e3-9595-30c6e04bb6cb.png)

Any thoughts?

**Comment by catskul** [comment]
Having the same issue.

**Comment by catskul** [comment]
Switched pages, came back, and it started working.

**Comment by jmerdich** [comment]
Another note: this is also triggered by django's view decorators (eg. `@login_required`), as wrapped functions don't seem to stick around long enough to act as the root function, and thus it defaults to the disable function (or in #9, throws an AssertionError) .

**Comment by PCreations** [comment]
I was struggling with the same issue and it seems there is no issue when the class based view does not override dispatch method.

**Comment by luster** [comment]
@jmerdich is there no workaround if you have django's view decorators enabled on a view?

**Comment by otrenav** [comment]
We solved this issue with a decorator that *conditionally* applies the decorators we applied previously. The condition is whether we have `DEBUG = True`. Hope this helps others with the same issue.
