### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by pahaz** [dmclain/django-debug-toolbar-line-profiler#7]
Please write some information about that in docs ...

**Comment by pahaz** [comment]
https://github.com/dmclain/django-debug-toolbar-line-profiler/blob/master/debug_toolbar_line_profiler/panel.py#L168 

https://docs.python.org/3.1/whatsnew/3.0.html#operators-and-special-methods

Now you must use:

    view_func.__globals__['__name__']

**Comment by pahaz** [comment]
patch: https://github.com/dmclain/django-debug-toolbar-line-profiler/pull/8

**Comment by btoueg** [comment]
Thanks :100:

**Comment by dmclain** [comment]
hopefully should be working with django-debug-profiler==0.5.0
